export const MENU_LAYOUT = {
  DESIGN_WIDTH: 1280,
  DESIGN_HEIGHT: 720,

  FONT_FAMILY: "Comic Sans MS, cursive, sans-serif",
  FONT_WEIGHT: "400",

  COLOR_NORMAL: "#ffffff",
  COLOR_ACTIVE: "#ff41ff",
  COLOR_MUTED: "#888888",

  FONT_TITLE: 28,
  FONT_OPTION: 24,
  FONT_INFO: 24,
  FONT_TOUCH: 24,

  TEXT_RESOLUTION: 2,
  TEXT_PADDING_X: 8,
  TEXT_PADDING_Y: 4,

  TITLE_Y_RATIO: 0.52,
  CONTENT_Y_RATIO: 0.62,

  LEFT_X_RATIO: 0.32,
  RIGHT_X_RATIO: 0.72,

  NAV_X_RATIO: 0.2,
  INFO_X_RATIO: 0.48,
  ACTION_X_RATIO: 0.78,

  TOUCH_Y_RATIO: 520 / 720,

  SPACING_MIN: 26,
  SPACING_RATIO: 0.05,
  LIST_SPACING: 42,
  LIST_OFFSET: 120,
}
