export const PLAYER_MOVE_SPEED = 300
export const PLAYER_JUMP_FORCE = 650
export const PLAYER_DODGE_FORCE = -5000
export const PLAYER_DODGE_IFRAME_DURATION = 300
export const PLAYER_DODGE_STAMINA_COST = 20
export const PLAYER_JUMP_STAMINA_COST = 10
export const PLAYER_BURST_DURATION = 1200
